CREATE OR REPLACE TRIGGER project_status_change_trigger
BEFORE UPDATE OF PROJECT_STATUS ON OZU_PROJECTS
FOR EACH ROW
BEGIN
  IF NOT((:OLD.PROJECT_STATUS = 'P' AND :NEW.PROJECT_STATUS = 'S') OR
         (:OLD.PROJECT_STATUS = 'S' AND :NEW.PROJECT_STATUS IN ('C','F'))
  ) THEN
    RAISE_APPLICATION_ERROR(-20500,'STATUS OF PROJECT CAN ONLY BE CHANGED AS FOLLOWING P -> S -> C || F');
  END IF;
END;

CREATE OR REPLACE TRIGGER task_status_change_trigger
BEFORE UPDATE OF TASK_STATUS ON OZU_TASKS
FOR EACH ROW
BEGIN
  IF NOT((:OLD.TASK_STATUS = 'P' AND :NEW.TASK_STATUS = 'S') OR
         (:OLD.TASK_STATUS = 'S' AND :NEW.TASK_STATUS IN ('C','F'))
  ) THEN
    RAISE_APPLICATION_ERROR(-20501,'STATUS OF TASK CAN ONLY BE CHANGED AS FOLLOWING P -> S -> C || F');
  END IF;
END;

CREATE OR REPLACE TRIGGER project_leader_check
BEFORE INSERT OR UPDATE OF LEADER_ID ON OZU_PROJECTS
FOR EACH ROW
BEGIN
  IF NOT(:NEW.PROJECT_STATUS = 'P') THEN
    IF(:NEW.LEADER_ID IS NULL) THEN
      RAISE_APPLICATION_ERROR(-20502,'PROJECT MUST HAVE A LEADER UNLESS ITS STATUS IS P');
    END IF;
  END IF;
END;

