/* Project Leader Trigger Tests */
INSERT INTO OZU_PROJECTS(PROJECT_ID, PROJECT_NAME,
                         PROJECT_STATUS, PROJECT_START_DATE, PROJECT_END_DATE)
VALUES(2007,'UI DEVELOPMENT','P',CURRENT_DATE,CURRENT_DATE);

INSERT INTO OZU_PROJECTS(PROJECT_ID, PROJECT_NAME,
                         PROJECT_STATUS, PROJECT_START_DATE, PROJECT_END_DATE)
VALUES(2008,'WEB SITE DEVELOPMENT','S',CURRENT_DATE,CURRENT_DATE);

UPDATE OZU_PROJECTS SET LEADER_ID = 344166 WHERE PROJECT_ID = 2007;
UPDATE OZU_PROJECTS SET PROJECT_STATUS = 'S' WHERE PROJECT_ID = 2007;
UPDATE OZU_PROJECTS SET LEADER_ID = NULL WHERE PROJECT_ID = 2007;

DELETE FROM OZU_PROJECTS WHERE PROJECT_ID = 2007;
/**/

/* Member Count Trigger Test */
INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, TASK_ID, WORK_PERCENTAGE)
VALUES(2003,268721,3276,0.15);

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, TASK_ID, WORK_PERCENTAGE)
VALUES(2004,268721,3142,0.15);

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, TASK_ID, WORK_PERCENTAGE)
VALUES(2006,268721,3704,0.15);
/*TODO DELETE VE UPDATE İÇİN TESTLER YAPILACAK */
/**/