/* Project Leader Trigger Tests */
/* Inserting project with status P and NULL leader -- SUCCESS */
INSERT INTO OZU_PROJECTS(PROJECT_ID, PROJECT_NAME,
                         PROJECT_STATUS, PROJECT_START_DATE, PROJECT_END_DATE)
VALUES(2007,'UI DEVELOPMENT','P',CURRENT_DATE,CURRENT_DATE);

/* Inserting project with status S and NULL leader -- ERROR */
INSERT INTO OZU_PROJECTS(PROJECT_ID, PROJECT_NAME,
                         PROJECT_STATUS, PROJECT_START_DATE, PROJECT_END_DATE)
VALUES(2008,'WEB SITE DEVELOPMENT','S',CURRENT_DATE,CURRENT_DATE);

/* ASSIGNING A LEADER TO PROJECT 2007 THEN UPDATING IT'S STATUS*/
UPDATE OZU_PROJECTS SET LEADER_ID = 344166 WHERE PROJECT_ID = 2007;
UPDATE OZU_PROJECTS SET PROJECT_STATUS = 'S' WHERE PROJECT_ID = 2007;
/* THIS PART SHOULD GIVE ERROR BECAUSE PROJECT STATUS IS NOT P NOW */
UPDATE OZU_PROJECTS SET LEADER_ID = NULL WHERE PROJECT_ID = 2007;

/* Cleaning */
DELETE FROM OZU_PROJECTS WHERE PROJECT_ID = 2007;
/**/

/* Member Count Trigger Test */
/* Currently, Employee 268721 is member of 3 projects */
INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2003,268721,0.15);

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2004,268721,0.15);

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2006,268721,0.15); /* 6th Project - Error */

DELETE FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2004 AND EMPLOYEE_ID = 268721; /* Reducing the member count to 4 */

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2006,268721,0.15); /* Now Successful */

/* Cleaning */
DELETE FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2006 AND EMPLOYEE_ID = 268721;
DELETE FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2003 AND EMPLOYEE_ID = 268721;
/**/

/* Work Percentage Trigger Test */

/* The employee's total work percentage is 0.65 at the moment */
INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2003,268721,0.45); /* This dml gives error -> 0.65 + 0.45 = 1.1 */

INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2004,268721,0.35);/* This dml works without error -> 0.65 + 0.35 = 1 */

UPDATE OZU_PROJECT_TEAMS SET WORK_PERCENTAGE = 0.25 WHERE EMPLOYEE_ID = 268721 AND PROJECT_ID = 2004;
/* Now the total work percentage becomes 0.9, we can add 0.1 work percentage */
INSERT INTO OZU_PROJECT_TEAMS(PROJECT_ID, EMPLOYEE_ID, WORK_PERCENTAGE)
VALUES(2003,268721,0.1);

/* Cleaning */
DELETE FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2004 AND EMPLOYEE_ID = 268721;
DELETE FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2003 AND EMPLOYEE_ID = 268721;
/**/

/* Project Leader Check Trigger Test */

/* Employee 587191 is the manager of the employee 442461 */
/* Both are in the Project 2001's team. */
/* Employee 392051 is in another department and her manager is not in the Project 2001's team */

UPDATE OZU_PROJECTS SET LEADER_ID = 442461 WHERE PROJECT_ID = 2001; /*Error, 442461 cannot be project leader because her manager is in the team*/
UPDATE OZU_PROJECTS SET LEADER_ID = 392051 WHERE PROJECT_ID = 2001; /*Success, employee 392051's manager not in the team */
UPDATE OZU_PROJECTS SET LEADER_ID = 587191 WHERE PROJECT_ID = 2001; /*Success, Employee 587191 is manager */
/**/

/* AUDIT Tests */
UPDATE OZU_PROJECTS SET PROJECT_STATUS = 'S' WHERE PROJECT_ID = 2002;
UPDATE OZU_PROJECTS SET PROJECT_STATUS = 'S' WHERE PROJECT_ID = 2004;

UPDATE OZU_TASKS SET TASK_STATUS = 'S' WHERE TASK_ID = 3324;
UPDATE OZU_TASKS SET TASK_STATUS = 'S' WHERE TASK_ID = 3278;

SELECT * FROM OZU_AUDIT_PROJECTS;
SELECT * FROM OZU_AUDIT_TASKS;
/**/


/* Project and task complete trigger test */

/* After project's status become C or F , the project team will be disbanded */
/* All employees that have the project's tasks will deleted from emp_tasks table */
/* All tasks related to the project will be deleted from tasks table */
SELECT * FROM OZU_TASKS WHERE PROJECT_ID = 2002;
SELECT * FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2002;
SELECT * FROM OZU_EMP_TASKS WHERE TASK_ID IN (SELECT TASK_ID FROM OZU_TASKS WHERE PROJECT_ID = 2002);
UPDATE OZU_PROJECTS SET PROJECT_STATUS = 'F' WHERE PROJECT_ID = 2002;

SELECT * FROM OZU_TASKS WHERE PROJECT_ID = 2002;
SELECT * FROM OZU_PROJECT_TEAMS WHERE PROJECT_ID = 2002;
SELECT * FROM OZU_EMP_TASKS WHERE TASK_ID IN (SELECT TASK_ID FROM OZU_TASKS WHERE PROJECT_ID = 2002);
/**/
/* Task Complete Trigger Test */
/* After task's status become C or F , all employees with the given task in the emp_tasks table will be deleted */
SELECT * FROM OZU_EMP_TASKS WHERE TASK_ID = 3278;
UPDATE OZU_TASKS SET TASK_STATUS = 'C' WHERE TASK_ID = 3278;
SELECT * FROM OZU_EMP_TASKS WHERE TASK_ID = 3278;
/**/
