CREATE TABLE OZU_EMPLOYEES (
  EMPLOYEE_ID NUMBER(6) PRIMARY KEY,
  FIRST_NAME VARCHAR2(20)NOT NULL,
  LAST_NAME  VARCHAR2(25)NOT NULL,
  EMAIL      VARCHAR2(45)NOT NULL,
  SALARY     NUMBER   NOT NULL,
  TOTAL_WORK_PERCENTAGE NUMBER(1) NOT NULL,
  MEMBERSHIP_COUNT NUMBER(1),
  DEPARTMENT_ID NUMBER(4),
  CONSTRAINT "EMP_SALARY_MIN" CHECK (salary > 0) ENABLE,
  CONSTRAINT "MEMBER_MAX" CHECK (MEMBERSHIP_COUNT <= 5) ENABLE,
  CONSTRAINT "WORK_PER_MAX" CHECK (TOTAL_WORK_PERCENTAGE < 1) ENABLE,
  CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL") ENABLE,
  CONSTRAINT "EMP_ID_PK"
    PRIMARY KEY ("EMPLOYEE_ID") ENABLE,
  CONSTRAINT "DEPARTMENT_ID_FK"
    FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "OZU_DEPARTMENTS"("DEPARTMENT_ID") ENABLE
  );

CREATE TABLE OZU_PROJECTS (
  PROJECT_ID NUMBER(4) NOT NULL,
  LEADER_ID NUMBER(4),
  PROJECT_STATUS  VARCHAR2(1) NOT NULL,
  PROJECT_START_DATE DATE NOT NULL,
  PROJECT_END_DATE   DATE NOT NULL,
  CONSTRAINT "PROJECT_ID_PK"
    PRIMARY KEY ("PROJECT_ID") ENABLE,
  CONSTRAINT "LEADER_ID_FK"
    FOREIGN KEY ("LEADER_ID") REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE
);


CREATE TABLE OZU_TASKS(
  TASK_ID NUMBER NOT NULL,
  TASK_STATUS VARCHAR2(1) NOT NULL,
  TASK_START_DATE DATE,
  TASK_END_DATE DATE,
  PROJECT_ID NUMBER(4) NOT NULL,
  EMPLOYEE_ID NUMBER(6) NOT NULL,
  CONSTRAINT "TASK_STATUS_CONS"
    CHECK (TASK_STATUS IN ('C','P','S','F')) ENABLE,
  CONSTRAINT "TASK_ID_PK"
    PRIMARY KEY ("TASK_ID") ENABLE,
  CONSTRAINT "PROJECT_ID_FK"
    FOREIGN KEY ("PROJECT_ID")
    REFERENCES OZU_PROJECTS("PROJECT_ID") ENABLE,
  CONSTRAINT "EMPLOYEE_ID_FK"
    FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE
);

CREATE TABLE OZU_DEPARTMENTS (
  DEPARTMENT_ID NUMBER(4) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(25) NOT NULL,
  HEAD_ID NUMBER(6) NOT NULL,
  CONSTRAINT "DEPT_ID_PK"
    PRIMARY KEY ("DEPARTMENT_ID") ENABLE,
  CONSTRAINT "HEAD_ID_FK"
    FOREIGN KEY ("HEAD_ID")
    REFERENCES OZU_EMPLOYEES("EMPLOYEE_ID") ENABLE
);

CREATE TABLE OZU_PROJECT_TEAMS (
  PROJECT_ID NUMBER(4) NOT NULL,
  EMPLOYEE_ID NUMBER(6) NOT NULL,
  TASK_ID NUMBER(4) NOT NULL,
  WORK_PERCENTAGE NUMBER NOT NULL,
  CONSTRAINT "PROJECT_ID_FK"
    FOREIGN KEY ("PROJECT_ID")
    REFERENCES OZU_PROJECTS("PROJECT_ID") ENABLE,
  CONSTRAINT "EMPLOYEE_ID_FK"
    FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES OZU_EMPLOYEES("EMPLOYEE_ID") ENABLE,
  CONSTRAINT "TASK_ID_FK"
    FOREIGN KEY ("TASK_ID")
    REFERENCES OZU_TASKS("TASK_ID") ENABLE,
  CONSTRAINT "WORK_PER_CONS"
    CHECK (0< WORK_PERCENTAGE < 1) ENABLE
);


