CREATE TABLE OZU_EMPLOYEES (
  EMPLOYEE_ID NUMBER(6) NOT NULL,
  FIRST_NAME VARCHAR2(20)NOT NULL,
  LAST_NAME  VARCHAR2(25)NOT NULL,
  EMAIL      VARCHAR2(45)NOT NULL,
  SALARY     NUMBER   NOT NULL,
  TOTAL_WORK_PERCENTAGE NUMBER(1) NOT NULL,
  MEMBERSHIP_COUNT NUMBER(1),
  DEPARTMENT_ID NUMBER(4),
  CONSTRAINT "OZU_EMP_SALARY_MIN" CHECK (salary > 0) ENABLE,
  CONSTRAINT "OZU_MEMBER_MAX" CHECK (MEMBERSHIP_COUNT <= 5) ENABLE,
  CONSTRAINT "OZU_WORK_PER_MAX" CHECK (TOTAL_WORK_PERCENTAGE < 1) ENABLE,
  CONSTRAINT "OZU_EMP_EMAIL_UK" UNIQUE ("EMAIL") ENABLE,
  CONSTRAINT "OZU_EMP_ID_PK"
    PRIMARY KEY ("EMPLOYEE_ID") ENABLE
  );

CREATE TABLE OZU_PROJECTS (
  PROJECT_ID NUMBER(4) NOT NULL,
  LEADER_ID NUMBER(4),
  PROJECT_STATUS  VARCHAR2(1) NOT NULL,
  PROJECT_START_DATE DATE NOT NULL,
  PROJECT_END_DATE   DATE NOT NULL,
  CONSTRAINT "OZU_PROJECT_ID_PK"
    PRIMARY KEY ("PROJECT_ID") ENABLE
);


CREATE TABLE OZU_TASKS(
  TASK_ID NUMBER NOT NULL,
  TASK_STATUS VARCHAR2(1) NOT NULL,
  TASK_START_DATE DATE,
  TASK_END_DATE DATE,
  PROJECT_ID NUMBER(4) NOT NULL,
  EMPLOYEE_ID NUMBER(6) NOT NULL,
  CONSTRAINT "OZU_TASK_STATUS_CONS"
    CHECK (TASK_STATUS IN ('C','P','S','F')) ENABLE,
  CONSTRAINT "OZU_TASK_ID_PK"
    PRIMARY KEY ("TASK_ID") ENABLE
);

CREATE TABLE OZU_DEPARTMENTS (
  DEPARTMENT_ID NUMBER(4) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(25) NOT NULL,
  HEAD_ID NUMBER(6) NOT NULL,
  CONSTRAINT "OZU_DEPT_ID_PK"
    PRIMARY KEY ("DEPARTMENT_ID") ENABLE
);

CREATE TABLE OZU_PROJECT_TEAMS (
  PROJECT_ID NUMBER(4) NOT NULL,
  EMPLOYEE_ID NUMBER(6) NOT NULL,
  TASK_ID NUMBER(4) NOT NULL,
  WORK_PERCENTAGE NUMBER NOT NULL,
  CONSTRAINT "OZU_TEAMS_WORK_PER_CONST"
    CHECK ("WORK_PERCENTAGE" <1) ENABLE
);

/* EMPLOYEE TABLE FK */
ALTER TABLE OZU_EMPLOYEES
  ADD CONSTRAINT "OZU_EMP_DEPARTMENT_ID_FK"
    FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "OZU_DEPARTMENTS"("DEPARTMENT_ID") ENABLE;

/* PROJECTS TABLE FK */
ALTER TABLE OZU_PROJECTS
  ADD CONSTRAINT "OZU_PROJ_LEADER_ID_FK"
    FOREIGN KEY ("LEADER_ID") REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE;

/* TASKS TABLE FK */
ALTER TABLE OZU_TASKS
  ADD CONSTRAINT "OZU_TASK_PROJECT_ID_FK"
    FOREIGN KEY ("PROJECT_ID")
    REFERENCES "OZU_PROJECTS"("PROJECT_ID") ENABLE;
ALTER TABLE OZU_TASKS
  ADD CONSTRAINT "OZU_TASK_EMPLOYEE_ID_FK"
    FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE;

/* DEPARTMENTS TABLE FK */
ALTER TABLE OZU_DEPARTMENTS
  ADD CONSTRAINT "OZU_DEPT_HEAD_ID_FK"
    FOREIGN KEY ("HEAD_ID")
    REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE;

/* PROJECT_TEAMS TABLE FK */
ALTER TABLE OZU_PROJECT_TEAMS
 ADD CONSTRAINT "OZU_TEAMS_PROJECT_ID_FK"
    FOREIGN KEY ("PROJECT_ID")
    REFERENCES "OZU_PROJECTS"("PROJECT_ID") ENABLE;
ALTER TABLE OZU_PROJECT_TEAMS
 ADD CONSTRAINT "OZU_TEAMS_EMPLOYEE_ID_FK"
    FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "OZU_EMPLOYEES"("EMPLOYEE_ID") ENABLE;
ALTER TABLE OZU_PROJECT_TEAMS
 ADD CONSTRAINT "OZU_TEAMS_TASK_ID_FK"
    FOREIGN KEY ("TASK_ID")
    REFERENCES "OZU_TASKS"("TASK_ID") ENABLE;
